plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

archivesBaseName = "${rootProject.mod_id}-fabric"
version = "${rootProject.mod_version}+mc${rootProject.minecraft_version}"

loom {
    silentMojangMappingsLicense()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment "org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_mappings_version}@zip"
    }

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modImplementation "dev.architectury:architectury-fabric:${rootProject.architectury_version}"
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    modCompileOnly "com.terraformersmc:modmenu:12.0.0"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionFabric')) { transitive = false }
    implementation 'it.unimi.dsi:fastutil:8.5.12'
}

processResources {
    inputs.property 'version', rootProject.mod_version
    filesMatching('fabric.mod.json') {
        expand 'version': rootProject.mod_version
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

jar {
    archiveClassifier = 'dev'
}
